export const PARKING_AND_GARAGES_NAICS_CODE = 812930;
export const SPECIAL_NEEDS_TRANSPORTATION_NAICS_CODE = 485991;
export const SDVOSB_SET_ASIDE_CODE = 'SDVOSBC';
export const SDVOSB_SOLE_SOURCE_CODE = 'SDVOSBS';
